# Generated by Django 2.0.13 on 2019-02-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190220_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='sent_time',
            new_name='send_time',
        ),
    ]
